--- # docker compose to build full stack app
version: "3.8"

services:
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - tedu-courses:/data/db
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      DB_CONNECTION_STRING: mongodb://db
      DB_NAME: tedu-courses
    volumes:
      - ./backend:/app
  backend-tests:
    image: full-stack-app_backend
    environment:
      DB_CONNECTION_STRING: mongodb://db
      DB_NAME: tedu-courses
    volumes:
      - ./backend:/app
    command: npm test
  frontend:
    build: ./frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
volumes:
  tedu-courses:
